# See: /usr/share/doc/mpd/mpdconf.example

bind_to_address "127.0.0.1"
port "6600"
music_directory "~/Music"
pid_file "~/.config/mpd/mpd.pid"
db_file "~/.config/mpd/mpd.db"
state_file "~/.config/mpd/mpdstate"
playlist_directory "~/Music/playlists"

audio_output {
	type          "pulse"
	name          "Pulse Output"
	#Optional
	#device        "iec958:CARD=Intel,DEV=0"
	mixer_control "PCM"
}

audio_output {
	type                    "fifo"
	name                    "my_fifo"
	path                    "/tmp/mpd.fifo"
	format                  "44100:16:2"
}
