#!/bin/sh
xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1366x768 --pos 0x152 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --mode 1280x1024 --pos 1366x0 --rotate normal
