#!/bin/sh
xrandr --output HDMI-0 --primary --mode 3840x2160 --pos 1920x0 --rotate normal --output DP-0 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --refresh 144 --off --output eDP-1-1 --off --output DP-1-1 --off --output HDMI-1-1 --off
~/.fehbg
i3-msg restart
