#!/bin/sh
xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1280x720 --pos 0x0 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --mode 1280x720 --pos 0x0 --rotate normal --output DP2 --off
~/.fehbg
i3-msg restart
