#!/usr/bin/env python

import argparse


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument("text", nargs="+")
    return parser.parse_args()


def main():
    args = parse_args()
    text = " ".join(args.text).lower()

    new_text = "".join(
        map(lambda d: d[1].upper() if d[0] % 2 == 0 else d[1], enumerate(text))
    )
    print(new_text)


if __name__ == "__main__":
    main()
