#!/bin/sh
xrandr --output HDMI-0 --primary --mode 3840x2160 --pos 0x0 --rotate normal --output DP-0 --off --output DP-1 --off --output eDP-1-1 --off --output DP-1-1 --off --output HDMI-1-1 --off
~/.fehbg
i3-msg restart
